config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :events
  resources :bands
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	has_one :venue
	has_many :performers
end

app/models/performer.rb
class Performer < ApplicationRecord
	has_many :events
end

app/models/venue.rb
class Venue < ApplicationRecord
	has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
	def show
		@band = Performer.find(params[:id])
	end

	def new
  	end

	def create
 		@band = Performer.new(band_params)
 
  		@band.save
 		redirect_to @band
	end
 
	private
  		def band_params
    		params.require(:band).permit(:name, :genre, :explicitlyrics)
 	 end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def show
		@event = Event.find(params[:id])
	end

	def new
  	end

	def create
 		@event = Event.new(event_params)
 
  		@event.save
 		redirect_to @event
	end
 
	private
  		def event_params
    		params.require(:event).permit(:date, :alcoholserved)
 	 end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
	def index
    	@venue = Venue.all
  	end

	def show
		@venue = Venue.find(params[:id])
	end

	def new
  	end

	def create
 		@venue = Venue.new(venue_params)
 
  		@venue.save
 		redirect_to @venue
	end
 
	private
  		def venue_params
    		params.require(:venue).permit(:name, :city, :state, :familyfriendly)
 	 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= form_for :band, url: bands_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :genre %><br>
    <%= f.text_area :genre %>
  </p>
  
  <p>
    <%= f.label :explicitlyrics %><br>
    <%= f.text_area :explicitlyrics %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/bands/show.html.erb
<p>
  <strong>Band Name:</strong>
  <%= @band.name %>
</p>
 
<p>
  <strong>Genre:</strong>
  <%= @band.genre %>
</p>

<p>
  <strong>Explicit Lyrics?</strong>
  <%= @band.exlicitlyrics %>
</p>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for :event, url: events_path do |f| %>
  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </p>
 
  <p>
    <%= f.label :alcoholserved %><br>
    <%= f.text_area :alcoholserved %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/events/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>
 
<p>
  <strong>Alcohol served?</strong>
  <%= @event.alcoholserved %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Band</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/venues/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>State</th>
    <th>Family Friendly?</th>
  </tr>
 
  <% @venue.each do |t| %>
    <tr>
      <td><%= t.name %></td>
      <td><%= t.city %></td>
      <td><%= t.state %></td>
      <td><%= t.familyfriendly %></td>
      <td><%= link_to 'Show', venue_path(t) %></td>
    </tr>
  <% end %>
</table>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= form_for :venue, url: venues_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :city %><br>
    <%= f.text_area :city %>
  </p>

    <p>
    <%= f.label :state %><br>
    <%= f.text_area :state %>
  </p>

    <p>
    <%= f.label :familyfriendly %><br>
    <%= f.text_area :familyfriendly %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/venues/show.html.erb
<p>
  <strong>Venue:</strong>
  <%= @venue.name %>
</p>
 
<p>
  <strong>City:</strong>
  <%= @venue.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @venue.state %>
</p>

<p>
  <strong>Family Friendly?</strong>
  <%= @venue.familyfriendly %>
</p>